import type { EnhancedPR } from '../types/github';

export const dummyPRs: EnhancedPR[] = [
  {
    id: 1,
    number: 123,
    title: 'Fix critical authentication bug',
    html_url: 'https://github.com/example/repo1/pull/123',
    state: 'open',
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), // 6 hours ago
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    user: {
      login: 'johndoe',
      id: 1,
      avatar_url: 'https://avatars.githubusercontent.com/u/1?v=4',
      html_url: 'https://github.com/johndoe',
    },
    assignees: [],
    requested_reviewers: [],
    labels: [
      { id: 1, name: 'urgent', color: 'd73a4a', description: 'Urgent PR' },
      { id: 2, name: 'bug', color: 'fc2929', description: 'Bug fix' },
    ],
    draft: false,
    head: { ref: 'fix/auth-bug' },
    base: { ref: 'main' },
    status: 'overdue',
    hoursOpen: 6,
    missingAssignee: true,
    missingReviewer: true,
    reviewerCount: 0,
    isUrgent: true,
    isQuick: false,    repo: {
      owner: 'acme-corp',
      name: 'backend-api',
    },
  },
  {
    id: 2,
    number: 456,
    title: 'Update dependencies to latest versions',
    html_url: 'https://github.com/example/repo1/pull/456',
    state: 'open',
    created_at: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(), // 3.5 hours ago
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    user: {
      login: 'janedoe',
      id: 2,
      avatar_url: 'https://avatars.githubusercontent.com/u/2?v=4',
      html_url: 'https://github.com/janedoe',
    },
    assignees: [
      {
        login: 'bobsmith',
        id: 3,
        avatar_url: 'https://avatars.githubusercontent.com/u/3?v=4',
        html_url: 'https://github.com/bobsmith',
      },
    ],
    requested_reviewers: [],
    labels: [
      { id: 3, name: 'dependencies', color: '0366d6', description: 'Dependencies update' },
    ],
    draft: false,
    head: { ref: 'deps/update-all' },
    base: { ref: 'main' },
    status: 'warning',
    hoursOpen: 3.5,
    missingAssignee: false,
    missingReviewer: true,
    reviewerCount: 0,
    isUrgent: false,
    isQuick: false,    repo: {
      owner: 'acme-corp',
      name: 'backend-api',
    },
  },
  {
    id: 3,
    number: 789,
    title: 'Add new payment gateway integration',
    html_url: 'https://github.com/example/repo2/pull/789',
    state: 'open',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    user: {
      login: 'alicejones',
      id: 4,
      avatar_url: 'https://avatars.githubusercontent.com/u/4?v=4',
      html_url: 'https://github.com/alicejones',
    },
    assignees: [
      {
        login: 'johndoe',
        id: 1,
        avatar_url: 'https://avatars.githubusercontent.com/u/1?v=4',
        html_url: 'https://github.com/johndoe',
      },
    ],
    requested_reviewers: [
      {
        login: 'janedoe',
        id: 2,
        avatar_url: 'https://avatars.githubusercontent.com/u/2?v=4',
        html_url: 'https://github.com/janedoe',
      },
    ],
    labels: [
      { id: 4, name: 'feature', color: 'a2eeef', description: 'New feature' },
      { id: 5, name: 'urgent', color: 'd73a4a', description: 'Urgent PR' },
    ],
    draft: false,
    head: { ref: 'feature/payment-gateway' },
    base: { ref: 'main' },
    status: 'ok',
    hoursOpen: 2,
    missingAssignee: false,
    missingReviewer: false,
    reviewerCount: 1,
    isUrgent: true,
    isQuick: false,    repo: {
      owner: 'acme-corp',
      name: 'frontend-app',
    },
  },
  {
    id: 4,
    number: 234,
    title: 'Refactor user authentication module',
    html_url: 'https://github.com/example/repo1/pull/234',
    state: 'open',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5 hours ago
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: {
      login: 'bobsmith',
      id: 3,
      avatar_url: 'https://avatars.githubusercontent.com/u/3?v=4',
      html_url: 'https://github.com/bobsmith',
    },
    assignees: [],
    requested_reviewers: [
      {
        login: 'alicejones',
        id: 4,
        avatar_url: 'https://avatars.githubusercontent.com/u/4?v=4',
        html_url: 'https://github.com/alicejones',
      },
    ],
    labels: [
      { id: 6, name: 'refactor', color: 'fbca04', description: 'Code refactoring' },
    ],
    draft: false,
    head: { ref: 'refactor/auth' },
    base: { ref: 'main' },
    status: 'overdue',
    hoursOpen: 5,
    missingAssignee: true,
    missingReviewer: false,
    reviewerCount: 1,
    isUrgent: false,
    isQuick: false,    repo: {
      owner: 'acme-corp',
      name: 'backend-api',
    },
  },
  {
    id: 5,
    number: 567,
    title: 'Update README with new setup instructions',
    html_url: 'https://github.com/example/repo2/pull/567',
    state: 'open',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    user: {
      login: 'janedoe',
      id: 2,
      avatar_url: 'https://avatars.githubusercontent.com/u/2?v=4',
      html_url: 'https://github.com/janedoe',
    },
    assignees: [
      {
        login: 'alicejones',
        id: 4,
        avatar_url: 'https://avatars.githubusercontent.com/u/4?v=4',
        html_url: 'https://github.com/alicejones',
      },
    ],
    requested_reviewers: [
      {
        login: 'bobsmith',
        id: 3,
        avatar_url: 'https://avatars.githubusercontent.com/u/3?v=4',
        html_url: 'https://github.com/bobsmith',
      },
      {
        login: 'johndoe',
        id: 1,
        avatar_url: 'https://avatars.githubusercontent.com/u/1?v=4',
        html_url: 'https://github.com/johndoe',
      },
    ],
    labels: [
      { id: 7, name: 'documentation', color: '0075ca', description: 'Documentation' },
    ],
    draft: false,
    head: { ref: 'docs/setup' },
    base: { ref: 'main' },
    status: 'ok',
    hoursOpen: 1,
    missingAssignee: false,
    missingReviewer: false,
    reviewerCount: 2,
    isUrgent: false,
    isQuick: false,    repo: {
      owner: 'acme-corp',
      name: 'frontend-app',
    },
  },
];
